### ISSUE TITLE
interested in collaborating?

### ISSUE THREAD

**Issue by karissa** [ralphtheninja/open-funding#2]
hey ralph,

This is a great idea. I know because I've also been thinking about doing this! I've been thinking about this with @nayafia. We met through this repo: https://github.com/pybee/paying-the-piper

We were thinking about putting together a survey and sending it out to folks in open source as well as within companies that use/contribute to oss to try to get some info on how people are funded as broadly as possible. This is totally necessary work! Do you want to help us at all?

**Comment by ralphtheninja** [comment]
> This is totally necessary work! Do you want to help us at all?

Of course I do! :)

**Comment by ralphtheninja** [comment]
@karissa Just let me know what you need help with

**Comment by ralphtheninja** [comment]
> We were thinking about putting together a survey and sending it out to folks in open source as well as within companies that use/contribute to oss to try to get some info on how people are funded as broadly as possible. This is totally necessary work! Do you want to help us at all?

The survey could be a simple form thingie that people could fill out. Maybe even store it on ipfs?

**Comment by nayafia** [comment]
hey Ralph! this is a great project. excited!

**Comment by ralphtheninja** [comment]
> hey Ralph! this is a great project. excited!

Thank you! It's about time we fund these geeks so they can just work on their crazy stuff. They know best anyway ;)
