### ISSUE TITLE
Add more notable projects (especially for OTF)

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/open-funding#21]

**Comment by matkoniecz** [comment]
OTF, as in "Open Technology Fund"?

**Comment by ralphtheninja** [comment]
> OTF, as in "Open Technology Fund"?

yep

**Comment by ralphtheninja** [comment]
DeltaChat is a good example.

**Comment by ralphtheninja** [comment]
About time I'm updating this. Added DeltaChat https://github.com/ralphtheninja/open-funding/commit/e4e0cafadd2883e56ef59f9612b4da61a86331dd
