### ISSUE TITLE
Add NLnet

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/open-funding#23]
https://nlnet.nl/news/2018/20181201-call-en.html

**Comment by ralphtheninja** [comment]
Added in https://github.com/ralphtheninja/open-funding/commit/5baf97ed271e838cdb544aaf26c85b123d29991d

**Comment by matkoniecz** [comment]
A bit offtopic: but I want to thank you for this issue, thanks to it I send a proposal that got funded (for https://github.com/westnordost/StreetComplete/)

**Comment by ralphtheninja** [comment]
@matkoniecz Very cool. Congratulations! :smile:

**Comment by ralphtheninja** [comment]
@matkoniecz Btw, very nice app. Going to use it in my neighborhood while walking my dog. Localization in Swedish also works really nice (not that it's really needed for me, but still).

**Comment by ralphtheninja** [comment]
@matkoniecz One last thing, since you seem really interested in maps you should definitely check out Peermaps, if you haven't. https://peermaps.org/ maybe they could also use your help?
