### ISSUE TITLE
samsung next

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/open-funding#27]
https://samsungnext.com/whats-next/introducing-the-samsung-next-stack-zero-grant/

**Comment by ralphtheninja** [comment]
Add peermaps as a notable project! They got $50k.

**Comment by TheTechRobo** [comment]
I can't find that anymore. Sure it still exists? If so, is there a link?

**Comment by matkoniecz** [comment]
Looking from results in https://duckduckgo.com/?q=samsung+next+stack+zero&t=canonical&ia=web that seems one time thing that is now in the past.

**Comment by TheTechRobo** [comment]
That's unfortunate. :/
