### ISSUE TITLE
Netidee.at

### ISSUE THREAD

**Issue by burnoutberni** [ralphtheninja/open-funding#30]
https://netidee.at/

Similar to InternetFonden in Sweden, run by a foundation around the Austrian .at TLD registry. Funding rounds once per year, max €50k. Focus on development of OSS.

**Comment by matkoniecz** [comment]
Is it officially restricted to Austria/Germany or is it done unofficially by not providing an English version of the pages?

**Comment by wilhelmy** [comment]
https://netidee.at/faq mentions that you have to be located in Austria. AFAIK the projects need some "relation with Austria", which I assume most projects creatively construct somehow in order to pass the selection process (most of the recipients don't seem to be particularly Austria related).

**Comment by ralphtheninja** [comment]
PR welcome :)

**Comment by wilhelmy** [comment]
See #34. Thanks for the repository :)

**Comment by ralphtheninja** [comment]
Added.
