### ISSUE TITLE
Mention "lemonade-stand" as another repo

### ISSUE THREAD

**Issue by TheTechRobo** [ralphtheninja/open-funding#42]
https://github.com/nayafia/lemonade-stand is another repo with these kinds of details. Maybe we could link to them?

**Comment by matkoniecz** [comment]
It is linked in "A handy guide to financial support for open source." added by my PR #32 - https://github.com/ralphtheninja/open-funding/pull/32/files

Maybe it can be better described.

**Comment by TheTechRobo** [comment]
Ah, sorry. Find&Replace didn't see it, so I got confused. Sorry for the invalid issue
