### ISSUE TITLE
delink dead https://github.com/jayfk/fundingoss.com ?

### ISSUE THREAD

**Issue by matkoniecz** [ralphtheninja/open-funding#47]
It is listed as "Funding OSS" and sadly appears to be thoroughly dead. I have not reviewed it yet is there some content worth rescuing there, and whether linked replacement should be linked

see https://github.com/jayfk/fundingoss.com

**Comment by matkoniecz** [comment]
Libraries.io's Experiments page: https://libraries.io/experiments/ also appears to be defunct

**Comment by ralphtheninja** [comment]
> It is listed as "Funding OSS" and sadly appears to be thoroughly dead. I have not reviewed it yet is there some content worth rescuing there, and whether linked replacement should be linked
> 
> see https://github.com/jayfk/fundingoss.com

Seems to be working fine.

**Comment by matkoniecz** [comment]
https://github.com/jayfk/fundingoss.com is a dead, archived and not maintained repository

is there anything interesting there?

http://fundingoss.com/ is linking some weird unrelated site

**Comment by ralphtheninja** [comment]
> https://github.com/jayfk/fundingoss.com is a dead, archived and not maintained repository
> 
> is there anything interesting there?
> 
> http://fundingoss.com/ is linking some weird unrelated site

Ah you're right. Lets remove it then.
