### ISSUE TITLE
updating funding options

### ISSUE THREAD

**Issue by serapath** [ralphtheninja/open-funding#49]
cheeeers :heart: :slightly_smiling_face: 
made a big document with a lot of funding programs for tech stuff.
it's sorted alphabetically.
i could make a pull request, but maybe you would want to change things first into having everything sorted alphabetically?

things are often busy and i just thought of this issue as a reminder to myself too. any preferences?

**Comment by ralphtheninja** [comment]
Yeah, I just didn't get around to it yet

**Comment by serapath** [comment]
Here is the list

https://hackmd.io/@T6Wf5EsOQKe-6wyPjJPtuw/rkXUfUfe3

**Comment by RichardLitt** [comment]
@serapath Happy to take a look if you want to make a PR?

**Comment by serapath** [comment]
Hey @RichardLitt
Wow, it's been a while 🙂 Sure, can do.

**Comment by ralphtheninja** [comment]
@serapath That is an amazing list! Maybe it's just easier to merge _this_ page into your already alphabetically ordered list?

**Comment by serapath** [comment]
https://github.com/ralphtheninja/open-funding/pull/62

I haven't updated the Table of Content. It feels like a lot of work and is it worth it?
A quick "search" might find you what you are looking for.

**Comment by RichardLitt** [comment]
Amazing! 

Take a look at #60 - it should be relatively easy to run that.

**Comment by ralphtheninja** [comment]
Awesome! There's quite a bit of formatting that should be identical but maybe we can just merge this right now. Lets generate the TOC once we're happy with the end result.

Some stuff to check:

- [ ] are there any multiples and/or redundant information
- [ ] use the same wording everywhere e.g. `N/A` or `...` or `???`
- [ ] Maybe even remove sub sections that doesn't have a deadline etc? several items have e.g. Application ... Deadline ??? etc
- [ ] some weird consecutive lines/sections, maybe due to empty text inbetween them?

**Comment by ralphtheninja** [comment]
@serapath Could you start by removing all the `{watch}`-thingies?

**Comment by serapath** [comment]
did remove it and a few extra separator lines.

so many programs. It was a full month of work.
We sent many applications. Nothing helped.
It was a frustrating experience.

Hope others have more luck.

**Comment by RichardLitt** [comment]
Thanks @serapath. I wish this had been more useful to you!

**Comment by ralphtheninja** [comment]
@RichardLitt @serapath I'd like to merge this right now and then I can make some PRs on top later with changes to style and whatnot.

**Comment by serapath** [comment]
My experience is, you have to be some sort of long term friend with the jury oe folks who run a grant program, otherwise you can never get anything.
not scalable and not fair. but it is what it is

**Comment by matkoniecz** [comment]
@serapath well, sometimes it works - I got nl.net funding despite (AFAIK) not knowing anyone there

**Comment by serapath** [comment]
What did you get it for?
Do you have a phd or work actively in academia?
Did you have somebody on your team who knows them or who introduced you?

We literally did not only not grt it, we also never got any feedback despite asking multiple times.
Treated with 0 respect.

**Comment by matkoniecz** [comment]
> What did you get it for?

https://github.com/ralphtheninja/open-funding?tab=readme-ov-file#streetcomplete

>  Do you have a phd or work actively in academia?

no (I have university-related contract but it was later and in UK)

>  Did you have somebody on your team who knows them or who introduced you?

no, went through open call

note that grant was relatively small
