### ISSUE TITLE
Add Sovereign Tech Fund

### ISSUE THREAD

**Issue by sergefdrv** [ralphtheninja/open-funding#50]
I think [STF](https://sovereigntechfund.de/en/)  should also be listed here.

**Comment by RichardLitt** [comment]
Agreed.

**Comment by mgifford** [comment]
Here's a brief PR https://github.com/ralphtheninja/open-funding/pull/51

There's much more in English now here too:
https://en.wikipedia.org/wiki/Sovereign_Tech_Fund
