### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by RichardLitt** [ralphtheninja/open-funding#52]
Hey @ralphtheninja  - I see this hasn't been updated in a while. Are you looking for more maintainers? Have you moved on from this unpaid project? Would you be interested in someone else taking over? 

Thank you. I'd be happy to fork it, but I want to check first.

**Comment by matkoniecz** [comment]
I see no outdated PRs, see https://github.com/ralphtheninja/open-funding/pulls?q=is%3Apr

#51 is only two days old

**Comment by matkoniecz** [comment]
So I would start from making PRs and consider forking when they are stale for long time.

**Comment by RichardLitt** [comment]
@matkoniecz Are you also a maintainer? If so, great. 

I'm looking at the open issues from a year ago, and that the README hasn't been updated in three years...

**Comment by matkoniecz** [comment]
> I'm looking at the open issues from a year ago

Well, to make PR you do not need to be a maintainer.

**Comment by ralphtheninja** [comment]
@RichardLitt Hey! Sorry I have been very inactive on github lately. I'd be happy to make you a maintainer to start with and I'll try to have a look in once in a while :)

**Comment by RichardLitt** [comment]
@ralphtheninja If you and @matkoniecz are maintainers and check it, I may not need to be added. Happy to make PRs and to help maintain this if it is something you want to keep going, though. Thank you.

**Comment by ralphtheninja** [comment]
@RichardLitt I forgot @matkoniecz was already a maintainer. Also added you though!

Wdyt about maybe cleaning this repo up a bit and converting it to a proper webpage?

**Comment by RichardLitt** [comment]
I think it's a good idea! However, I have some life stuff going on right now - moving internationally, hosting a conference - and my time will be limited for at least the next few weeks. I'll circle back, just a heads up.

**Comment by RichardLitt** [comment]
Cleaning the repo up makes sense to me. I think merging #49 would be the best avenue for that. 

I don't think that making a proper webpage is that important to me personally. The information works just as well on a README.
