### ISSUE TITLE
Add OTF RFP

### ISSUE THREAD

**Issue by RichardLitt** [ralphtheninja/open-funding#55]
What shall we do with RFPs like this one? https://www.opentech.fund/news/request-for-proposals-impact-engagement-lab/ Should they go in their own  time-bounded section?

**Comment by almereyda** [comment]
Information about similar requests would be very welcome. A separation from generic funding opportunities can be useful, yes.

**Comment by ralphtheninja** [comment]
At least it could be good to somehow indicate that it's time-bounded. Downside is that you need to update the document. We could also add a best before date (like for milk) and later clean that up.
