### ISSUE TITLE
Open Source Funding Research Survey from the Linux Foundation, Harvard University, and GitHub

### ISSUE THREAD

**Issue by RichardLitt** [ralphtheninja/open-funding#61]
Copied from @karasowles' post elsewhere: 

The Linux Foundation is partnering with GitHub and researchers from Harvard University to understand the motivations and mechanisms behind open source funding. Our objective is to better understand how organizations fund, contribute to, or support open source software projects. We are looking for OSPOs, Heads of Engineering and Product, C-Level Executives, and other individuals with a solid understanding of their organization's open source engagement to take our survey. If you are within an org and know how it funds (or doesn't fun) OSS, we'd love for you to take it. The survey closes August 16th.

💰 Take the survey: [linuxfoundation.org/research/surveys/open-source-software-funding-survey-2024](https://www.linuxfoundation.org/research/surveys/open-source-software-funding-survey-2024)

In addition, if you have organizations that are funding your project that you can pass this along to, it would be greatly appreciated. With your help, this research will enable more funding and support to take place and create a more sustainable open source ecosystem. Thank you!

---

I think this probably doesn't need to be added to the README, but figured it should be good as an issue. Should be closed next week after the 16th.

**Comment by matkoniecz** [comment]
https://www.linuxfoundation.org/research/surveys/open-source-software-funding-survey-2024 is now 404ing
